//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1008
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmidaServerService.PMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://winfoundry.com/", ConfigurationName="PMSService.WINServiceSoap")]
    public interface WINServiceSoap {
        
        // CODEGEN: 命名空間 http://winfoundry.com/ 的項目名稱  Para 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://winfoundry.com/PMS_MainService", ReplyAction="*")]
        AmidaServerService.PMSService.PMS_MainServiceResponse PMS_MainService(AmidaServerService.PMSService.PMS_MainServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainService", Namespace="http://winfoundry.com/", Order=0)]
        public AmidaServerService.PMSService.PMS_MainServiceRequestBody Body;
        
        public PMS_MainServiceRequest() {
        }
        
        public PMS_MainServiceRequest(AmidaServerService.PMSService.PMS_MainServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Para;
        
        public PMS_MainServiceRequestBody() {
        }
        
        public PMS_MainServiceRequestBody(string Para) {
            this.Para = Para;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainServiceResponse", Namespace="http://winfoundry.com/", Order=0)]
        public AmidaServerService.PMSService.PMS_MainServiceResponseBody Body;
        
        public PMS_MainServiceResponse() {
        }
        
        public PMS_MainServiceResponse(AmidaServerService.PMSService.PMS_MainServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PMS_MainServiceResult;
        
        public PMS_MainServiceResponseBody() {
        }
        
        public PMS_MainServiceResponseBody(string PMS_MainServiceResult) {
            this.PMS_MainServiceResult = PMS_MainServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WINServiceSoapChannel : AmidaServerService.PMSService.WINServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WINServiceSoapClient : System.ServiceModel.ClientBase<AmidaServerService.PMSService.WINServiceSoap>, AmidaServerService.PMSService.WINServiceSoap {
        
        public WINServiceSoapClient() {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WINServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmidaServerService.PMSService.PMS_MainServiceResponse AmidaServerService.PMSService.WINServiceSoap.PMS_MainService(AmidaServerService.PMSService.PMS_MainServiceRequest request) {
            return base.Channel.PMS_MainService(request);
        }
        
        public string PMS_MainService(string Para) {
            AmidaServerService.PMSService.PMS_MainServiceRequest inValue = new AmidaServerService.PMSService.PMS_MainServiceRequest();
            inValue.Body = new AmidaServerService.PMSService.PMS_MainServiceRequestBody();
            inValue.Body.Para = Para;
            AmidaServerService.PMSService.PMS_MainServiceResponse retVal = ((AmidaServerService.PMSService.WINServiceSoap)(this)).PMS_MainService(inValue);
            return retVal.Body.PMS_MainServiceResult;
        }
    }
}
