//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1008
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.PMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://winfoundry.com/", ConfigurationName="PMSService.WINServiceSoap")]
    public interface WINServiceSoap {
        
        // CODEGEN: 命名空間 http://winfoundry.com/ 的項目名稱  Para 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://winfoundry.com/PMS_MainService", ReplyAction="*")]
        test.PMSService.PMS_MainServiceResponse PMS_MainService(test.PMSService.PMS_MainServiceRequest request);
        
        // CODEGEN: 命名空間 http://winfoundry.com/ 的項目名稱  Para 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://winfoundry.com/PMS_MainService_File", ReplyAction="*")]
        test.PMSService.PMS_MainService_FileResponse PMS_MainService_File(test.PMSService.PMS_MainService_FileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainService", Namespace="http://winfoundry.com/", Order=0)]
        public test.PMSService.PMS_MainServiceRequestBody Body;
        
        public PMS_MainServiceRequest() {
        }
        
        public PMS_MainServiceRequest(test.PMSService.PMS_MainServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Para;
        
        public PMS_MainServiceRequestBody() {
        }
        
        public PMS_MainServiceRequestBody(string Para) {
            this.Para = Para;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainServiceResponse", Namespace="http://winfoundry.com/", Order=0)]
        public test.PMSService.PMS_MainServiceResponseBody Body;
        
        public PMS_MainServiceResponse() {
        }
        
        public PMS_MainServiceResponse(test.PMSService.PMS_MainServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PMS_MainServiceResult;
        
        public PMS_MainServiceResponseBody() {
        }
        
        public PMS_MainServiceResponseBody(string PMS_MainServiceResult) {
            this.PMS_MainServiceResult = PMS_MainServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainService_FileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainService_File", Namespace="http://winfoundry.com/", Order=0)]
        public test.PMSService.PMS_MainService_FileRequestBody Body;
        
        public PMS_MainService_FileRequest() {
        }
        
        public PMS_MainService_FileRequest(test.PMSService.PMS_MainService_FileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainService_FileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Para;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] FileByte;
        
        public PMS_MainService_FileRequestBody() {
        }
        
        public PMS_MainService_FileRequestBody(string Para, byte[] FileByte) {
            this.Para = Para;
            this.FileByte = FileByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PMS_MainService_FileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PMS_MainService_FileResponse", Namespace="http://winfoundry.com/", Order=0)]
        public test.PMSService.PMS_MainService_FileResponseBody Body;
        
        public PMS_MainService_FileResponse() {
        }
        
        public PMS_MainService_FileResponse(test.PMSService.PMS_MainService_FileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://winfoundry.com/")]
    public partial class PMS_MainService_FileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PMS_MainService_FileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] FileByte;
        
        public PMS_MainService_FileResponseBody() {
        }
        
        public PMS_MainService_FileResponseBody(string PMS_MainService_FileResult, byte[] FileByte) {
            this.PMS_MainService_FileResult = PMS_MainService_FileResult;
            this.FileByte = FileByte;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WINServiceSoapChannel : test.PMSService.WINServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WINServiceSoapClient : System.ServiceModel.ClientBase<test.PMSService.WINServiceSoap>, test.PMSService.WINServiceSoap {
        
        public WINServiceSoapClient() {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WINServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WINServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.PMSService.PMS_MainServiceResponse test.PMSService.WINServiceSoap.PMS_MainService(test.PMSService.PMS_MainServiceRequest request) {
            return base.Channel.PMS_MainService(request);
        }
        
        public string PMS_MainService(string Para) {
            test.PMSService.PMS_MainServiceRequest inValue = new test.PMSService.PMS_MainServiceRequest();
            inValue.Body = new test.PMSService.PMS_MainServiceRequestBody();
            inValue.Body.Para = Para;
            test.PMSService.PMS_MainServiceResponse retVal = ((test.PMSService.WINServiceSoap)(this)).PMS_MainService(inValue);
            return retVal.Body.PMS_MainServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.PMSService.PMS_MainService_FileResponse test.PMSService.WINServiceSoap.PMS_MainService_File(test.PMSService.PMS_MainService_FileRequest request) {
            return base.Channel.PMS_MainService_File(request);
        }
        
        public string PMS_MainService_File(string Para, ref byte[] FileByte) {
            test.PMSService.PMS_MainService_FileRequest inValue = new test.PMSService.PMS_MainService_FileRequest();
            inValue.Body = new test.PMSService.PMS_MainService_FileRequestBody();
            inValue.Body.Para = Para;
            inValue.Body.FileByte = FileByte;
            test.PMSService.PMS_MainService_FileResponse retVal = ((test.PMSService.WINServiceSoap)(this)).PMS_MainService_File(inValue);
            FileByte = retVal.Body.FileByte;
            return retVal.Body.PMS_MainService_FileResult;
        }
    }
}
