//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace test
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class AmidaEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'AmidaEntities' 區段中找到的連接字串，初始化新的 AmidaEntities 物件。
        /// </summary>
        public AmidaEntities() : base("name=AmidaEntities", "AmidaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AmidaEntities 物件。
        /// </summary>
        public AmidaEntities(string connectionString) : base(connectionString, "AmidaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 AmidaEntities 物件。
        /// </summary>
        public AmidaEntities(EntityConnection connection) : base(connection, "AmidaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblEQHistory> tblEQHistory
        {
            get
            {
                if ((_tblEQHistory == null))
                {
                    _tblEQHistory = base.CreateObjectSet<tblEQHistory>("tblEQHistory");
                }
                return _tblEQHistory;
            }
        }
        private ObjectSet<tblEQHistory> _tblEQHistory;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblEQ> tblEQ
        {
            get
            {
                if ((_tblEQ == null))
                {
                    _tblEQ = base.CreateObjectSet<tblEQ>("tblEQ");
                }
                return _tblEQ;
            }
        }
        private ObjectSet<tblEQ> _tblEQ;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblEQHistory EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblEQHistory(tblEQHistory tblEQHistory)
        {
            base.AddObject("tblEQHistory", tblEQHistory);
        }
    
        /// <summary>
        /// 將新物件加入 tblEQ EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblEQ(tblEQ tblEQ)
        {
            base.AddObject("tblEQ", tblEQ);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmidaModel", Name="tblEQ")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblEQ : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblEQ 物件。
        /// </summary>
        /// <param name="eqi_id">eqi_id 屬性的初始值。</param>
        /// <param name="eq_release_time">eq_release_time 屬性的初始值。</param>
        /// <param name="total_num_wafer">total_num_wafer 屬性的初始值。</param>
        /// <param name="tested_num_wafer">tested_num_wafer 屬性的初始值。</param>
        /// <param name="total_num_chip">total_num_chip 屬性的初始值。</param>
        /// <param name="tested_num_chip">tested_num_chip 屬性的初始值。</param>
        /// <param name="isWarnig">IsWarnig 屬性的初始值。</param>
        public static tblEQ CreatetblEQ(global::System.String eqi_id, global::System.DateTime eq_release_time, global::System.Int32 total_num_wafer, global::System.Int32 tested_num_wafer, global::System.Int32 total_num_chip, global::System.Int32 tested_num_chip, global::System.String isWarnig)
        {
            tblEQ tblEQ = new tblEQ();
            tblEQ.eqi_id = eqi_id;
            tblEQ.eq_release_time = eq_release_time;
            tblEQ.total_num_wafer = total_num_wafer;
            tblEQ.tested_num_wafer = tested_num_wafer;
            tblEQ.total_num_chip = total_num_chip;
            tblEQ.tested_num_chip = tested_num_chip;
            tblEQ.IsWarnig = isWarnig;
            return tblEQ;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eqi_id
        {
            get
            {
                return _eqi_id;
            }
            set
            {
                if (_eqi_id != value)
                {
                    Oneqi_idChanging(value);
                    ReportPropertyChanging("eqi_id");
                    _eqi_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("eqi_id");
                    Oneqi_idChanged();
                }
            }
        }
        private global::System.String _eqi_id;
        partial void Oneqi_idChanging(global::System.String value);
        partial void Oneqi_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_type
        {
            get
            {
                return _eq_type;
            }
            set
            {
                Oneq_typeChanging(value);
                ReportPropertyChanging("eq_type");
                _eq_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_type");
                Oneq_typeChanged();
            }
        }
        private global::System.String _eq_type;
        partial void Oneq_typeChanging(global::System.String value);
        partial void Oneq_typeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_prober
        {
            get
            {
                return _eq_prober;
            }
            set
            {
                Oneq_proberChanging(value);
                ReportPropertyChanging("eq_prober");
                _eq_prober = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_prober");
                Oneq_proberChanged();
            }
        }
        private global::System.String _eq_prober;
        partial void Oneq_proberChanging(global::System.String value);
        partial void Oneq_proberChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_tester
        {
            get
            {
                return _eq_tester;
            }
            set
            {
                Oneq_testerChanging(value);
                ReportPropertyChanging("eq_tester");
                _eq_tester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_tester");
                Oneq_testerChanged();
            }
        }
        private global::System.String _eq_tester;
        partial void Oneq_testerChanging(global::System.String value);
        partial void Oneq_testerChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime eq_release_time
        {
            get
            {
                return _eq_release_time;
            }
            set
            {
                Oneq_release_timeChanging(value);
                ReportPropertyChanging("eq_release_time");
                _eq_release_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eq_release_time");
                Oneq_release_timeChanged();
            }
        }
        private global::System.DateTime _eq_release_time;
        partial void Oneq_release_timeChanging(global::System.DateTime value);
        partial void Oneq_release_timeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_comment
        {
            get
            {
                return _eq_comment;
            }
            set
            {
                Oneq_commentChanging(value);
                ReportPropertyChanging("eq_comment");
                _eq_comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_comment");
                Oneq_commentChanged();
            }
        }
        private global::System.String _eq_comment;
        partial void Oneq_commentChanging(global::System.String value);
        partial void Oneq_commentChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lot_id
        {
            get
            {
                return _lot_id;
            }
            set
            {
                Onlot_idChanging(value);
                ReportPropertyChanging("lot_id");
                _lot_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lot_id");
                Onlot_idChanged();
            }
        }
        private global::System.String _lot_id;
        partial void Onlot_idChanging(global::System.String value);
        partial void Onlot_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String probe_card_id
        {
            get
            {
                return _probe_card_id;
            }
            set
            {
                Onprobe_card_idChanging(value);
                ReportPropertyChanging("probe_card_id");
                _probe_card_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("probe_card_id");
                Onprobe_card_idChanged();
            }
        }
        private global::System.String _probe_card_id;
        partial void Onprobe_card_idChanging(global::System.String value);
        partial void Onprobe_card_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_time;
        partial void Onstart_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recipe
        {
            get
            {
                return _recipe;
            }
            set
            {
                OnrecipeChanging(value);
                ReportPropertyChanging("recipe");
                _recipe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recipe");
                OnrecipeChanged();
            }
        }
        private global::System.String _recipe;
        partial void OnrecipeChanging(global::System.String value);
        partial void OnrecipeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @operator
        {
            get
            {
                return _operator;
            }
            set
            {
                OnoperatorChanging(value);
                ReportPropertyChanging("operator");
                _operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("operator");
                OnoperatorChanged();
            }
        }
        private global::System.String _operator;
        partial void OnoperatorChanging(global::System.String value);
        partial void OnoperatorChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total_num_wafer
        {
            get
            {
                return _total_num_wafer;
            }
            set
            {
                Ontotal_num_waferChanging(value);
                ReportPropertyChanging("total_num_wafer");
                _total_num_wafer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_num_wafer");
                Ontotal_num_waferChanged();
            }
        }
        private global::System.Int32 _total_num_wafer;
        partial void Ontotal_num_waferChanging(global::System.Int32 value);
        partial void Ontotal_num_waferChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fab
        {
            get
            {
                return _fab;
            }
            set
            {
                OnfabChanging(value);
                ReportPropertyChanging("fab");
                _fab = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fab");
                OnfabChanged();
            }
        }
        private global::System.String _fab;
        partial void OnfabChanging(global::System.String value);
        partial void OnfabChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tested_num_wafer
        {
            get
            {
                return _tested_num_wafer;
            }
            set
            {
                Ontested_num_waferChanging(value);
                ReportPropertyChanging("tested_num_wafer");
                _tested_num_wafer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tested_num_wafer");
                Ontested_num_waferChanged();
            }
        }
        private global::System.Int32 _tested_num_wafer;
        partial void Ontested_num_waferChanging(global::System.Int32 value);
        partial void Ontested_num_waferChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 total_num_chip
        {
            get
            {
                return _total_num_chip;
            }
            set
            {
                Ontotal_num_chipChanging(value);
                ReportPropertyChanging("total_num_chip");
                _total_num_chip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_num_chip");
                Ontotal_num_chipChanged();
            }
        }
        private global::System.Int32 _total_num_chip;
        partial void Ontotal_num_chipChanging(global::System.Int32 value);
        partial void Ontotal_num_chipChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tested_num_chip
        {
            get
            {
                return _tested_num_chip;
            }
            set
            {
                Ontested_num_chipChanging(value);
                ReportPropertyChanging("tested_num_chip");
                _tested_num_chip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tested_num_chip");
                Ontested_num_chipChanged();
            }
        }
        private global::System.Int32 _tested_num_chip;
        partial void Ontested_num_chipChanging(global::System.Int32 value);
        partial void Ontested_num_chipChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String current_test_wafer_id
        {
            get
            {
                return _current_test_wafer_id;
            }
            set
            {
                Oncurrent_test_wafer_idChanging(value);
                ReportPropertyChanging("current_test_wafer_id");
                _current_test_wafer_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("current_test_wafer_id");
                Oncurrent_test_wafer_idChanged();
            }
        }
        private global::System.String _current_test_wafer_id;
        partial void Oncurrent_test_wafer_idChanging(global::System.String value);
        partial void Oncurrent_test_wafer_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsWarnig
        {
            get
            {
                return _IsWarnig;
            }
            set
            {
                OnIsWarnigChanging(value);
                ReportPropertyChanging("IsWarnig");
                _IsWarnig = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsWarnig");
                OnIsWarnigChanged();
            }
        }
        private global::System.String _IsWarnig;
        partial void OnIsWarnigChanging(global::System.String value);
        partial void OnIsWarnigChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> current_identify
        {
            get
            {
                return _current_identify;
            }
            set
            {
                Oncurrent_identifyChanging(value);
                ReportPropertyChanging("current_identify");
                _current_identify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("current_identify");
                Oncurrent_identifyChanged();
            }
        }
        private Nullable<global::System.Int64> _current_identify;
        partial void Oncurrent_identifyChanging(Nullable<global::System.Int64> value);
        partial void Oncurrent_identifyChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> expected_remain_time
        {
            get
            {
                return _expected_remain_time;
            }
            set
            {
                Onexpected_remain_timeChanging(value);
                ReportPropertyChanging("expected_remain_time");
                _expected_remain_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("expected_remain_time");
                Onexpected_remain_timeChanged();
            }
        }
        private Nullable<global::System.Int32> _expected_remain_time;
        partial void Onexpected_remain_timeChanging(Nullable<global::System.Int32> value);
        partial void Onexpected_remain_timeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> current_warning_identify
        {
            get
            {
                return _current_warning_identify;
            }
            set
            {
                Oncurrent_warning_identifyChanging(value);
                ReportPropertyChanging("current_warning_identify");
                _current_warning_identify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("current_warning_identify");
                Oncurrent_warning_identifyChanged();
            }
        }
        private Nullable<global::System.Int32> _current_warning_identify;
        partial void Oncurrent_warning_identifyChanging(Nullable<global::System.Int32> value);
        partial void Oncurrent_warning_identifyChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_area
        {
            get
            {
                return _eq_area;
            }
            set
            {
                Oneq_areaChanging(value);
                ReportPropertyChanging("eq_area");
                _eq_area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_area");
                Oneq_areaChanged();
            }
        }
        private global::System.String _eq_area;
        partial void Oneq_areaChanging(global::System.String value);
        partial void Oneq_areaChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wafer_id
        {
            get
            {
                return _wafer_id;
            }
            set
            {
                Onwafer_idChanging(value);
                ReportPropertyChanging("wafer_id");
                _wafer_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wafer_id");
                Onwafer_idChanged();
            }
        }
        private global::System.String _wafer_id;
        partial void Onwafer_idChanging(global::System.String value);
        partial void Onwafer_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> over_drift
        {
            get
            {
                return _over_drift;
            }
            set
            {
                Onover_driftChanging(value);
                ReportPropertyChanging("over_drift");
                _over_drift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("over_drift");
                Onover_driftChanged();
            }
        }
        private Nullable<global::System.Double> _over_drift;
        partial void Onover_driftChanging(Nullable<global::System.Double> value);
        partial void Onover_driftChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sub_status
        {
            get
            {
                return _sub_status;
            }
            set
            {
                Onsub_statusChanging(value);
                ReportPropertyChanging("sub_status");
                _sub_status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sub_status");
                Onsub_statusChanged();
            }
        }
        private global::System.String _sub_status;
        partial void Onsub_statusChanging(global::System.String value);
        partial void Onsub_statusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AmidaModel", Name="tblEQHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblEQHistory : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblEQHistory 物件。
        /// </summary>
        /// <param name="identify">identify 屬性的初始值。</param>
        /// <param name="eq_id">eq_id 屬性的初始值。</param>
        /// <param name="status">status 屬性的初始值。</param>
        /// <param name="start_time">start_time 屬性的初始值。</param>
        /// <param name="isFinish">IsFinish 屬性的初始值。</param>
        public static tblEQHistory CreatetblEQHistory(global::System.Int64 identify, global::System.String eq_id, global::System.String status, global::System.DateTime start_time, global::System.Boolean isFinish)
        {
            tblEQHistory tblEQHistory = new tblEQHistory();
            tblEQHistory.identify = identify;
            tblEQHistory.eq_id = eq_id;
            tblEQHistory.status = status;
            tblEQHistory.start_time = start_time;
            tblEQHistory.IsFinish = isFinish;
            return tblEQHistory;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 identify
        {
            get
            {
                return _identify;
            }
            set
            {
                if (_identify != value)
                {
                    OnidentifyChanging(value);
                    ReportPropertyChanging("identify");
                    _identify = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identify");
                    OnidentifyChanged();
                }
            }
        }
        private global::System.Int64 _identify;
        partial void OnidentifyChanging(global::System.Int64 value);
        partial void OnidentifyChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eq_id
        {
            get
            {
                return _eq_id;
            }
            set
            {
                Oneq_idChanging(value);
                ReportPropertyChanging("eq_id");
                _eq_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eq_id");
                Oneq_idChanged();
            }
        }
        private global::System.String _eq_id;
        partial void Oneq_idChanging(global::System.String value);
        partial void Oneq_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lot_id
        {
            get
            {
                return _lot_id;
            }
            set
            {
                Onlot_idChanging(value);
                ReportPropertyChanging("lot_id");
                _lot_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lot_id");
                Onlot_idChanged();
            }
        }
        private global::System.String _lot_id;
        partial void Onlot_idChanging(global::System.String value);
        partial void Onlot_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String probe_card_id
        {
            get
            {
                return _probe_card_id;
            }
            set
            {
                Onprobe_card_idChanging(value);
                ReportPropertyChanging("probe_card_id");
                _probe_card_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("probe_card_id");
                Onprobe_card_idChanged();
            }
        }
        private global::System.String _probe_card_id;
        partial void Onprobe_card_idChanging(global::System.String value);
        partial void Onprobe_card_idChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String recipe
        {
            get
            {
                return _recipe;
            }
            set
            {
                OnrecipeChanging(value);
                ReportPropertyChanging("recipe");
                _recipe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("recipe");
                OnrecipeChanged();
            }
        }
        private global::System.String _recipe;
        partial void OnrecipeChanging(global::System.String value);
        partial void OnrecipeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> total_num_wafer
        {
            get
            {
                return _total_num_wafer;
            }
            set
            {
                Ontotal_num_waferChanging(value);
                ReportPropertyChanging("total_num_wafer");
                _total_num_wafer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_num_wafer");
                Ontotal_num_waferChanged();
            }
        }
        private Nullable<global::System.Int32> _total_num_wafer;
        partial void Ontotal_num_waferChanging(Nullable<global::System.Int32> value);
        partial void Ontotal_num_waferChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String @operator
        {
            get
            {
                return _operator;
            }
            set
            {
                OnoperatorChanging(value);
                ReportPropertyChanging("operator");
                _operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("operator");
                OnoperatorChanged();
            }
        }
        private global::System.String _operator;
        partial void OnoperatorChanging(global::System.String value);
        partial void OnoperatorChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private global::System.DateTime _start_time;
        partial void Onstart_timeChanging(global::System.DateTime value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> stop_time
        {
            get
            {
                return _stop_time;
            }
            set
            {
                Onstop_timeChanging(value);
                ReportPropertyChanging("stop_time");
                _stop_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stop_time");
                Onstop_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _stop_time;
        partial void Onstop_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onstop_timeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eq_comment
        {
            get
            {
                return _eq_comment;
            }
            set
            {
                Oneq_commentChanging(value);
                ReportPropertyChanging("eq_comment");
                _eq_comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eq_comment");
                Oneq_commentChanged();
            }
        }
        private global::System.String _eq_comment;
        partial void Oneq_commentChanging(global::System.String value);
        partial void Oneq_commentChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFinish
        {
            get
            {
                return _IsFinish;
            }
            set
            {
                OnIsFinishChanging(value);
                ReportPropertyChanging("IsFinish");
                _IsFinish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFinish");
                OnIsFinishChanged();
            }
        }
        private global::System.Boolean _IsFinish;
        partial void OnIsFinishChanging(global::System.Boolean value);
        partial void OnIsFinishChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tested_num_wafer
        {
            get
            {
                return _tested_num_wafer;
            }
            set
            {
                Ontested_num_waferChanging(value);
                ReportPropertyChanging("tested_num_wafer");
                _tested_num_wafer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tested_num_wafer");
                Ontested_num_waferChanged();
            }
        }
        private Nullable<global::System.Int32> _tested_num_wafer;
        partial void Ontested_num_waferChanging(Nullable<global::System.Int32> value);
        partial void Ontested_num_waferChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wafer_id_in
        {
            get
            {
                return _wafer_id_in;
            }
            set
            {
                Onwafer_id_inChanging(value);
                ReportPropertyChanging("wafer_id_in");
                _wafer_id_in = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wafer_id_in");
                Onwafer_id_inChanged();
            }
        }
        private global::System.String _wafer_id_in;
        partial void Onwafer_id_inChanging(global::System.String value);
        partial void Onwafer_id_inChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wafer_id_out
        {
            get
            {
                return _wafer_id_out;
            }
            set
            {
                Onwafer_id_outChanging(value);
                ReportPropertyChanging("wafer_id_out");
                _wafer_id_out = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wafer_id_out");
                Onwafer_id_outChanged();
            }
        }
        private global::System.String _wafer_id_out;
        partial void Onwafer_id_outChanging(global::System.String value);
        partial void Onwafer_id_outChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> over_drift
        {
            get
            {
                return _over_drift;
            }
            set
            {
                Onover_driftChanging(value);
                ReportPropertyChanging("over_drift");
                _over_drift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("over_drift");
                Onover_driftChanged();
            }
        }
        private Nullable<global::System.Double> _over_drift;
        partial void Onover_driftChanging(Nullable<global::System.Double> value);
        partial void Onover_driftChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> over_drift_in
        {
            get
            {
                return _over_drift_in;
            }
            set
            {
                Onover_drift_inChanging(value);
                ReportPropertyChanging("over_drift_in");
                _over_drift_in = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("over_drift_in");
                Onover_drift_inChanged();
            }
        }
        private Nullable<global::System.Double> _over_drift_in;
        partial void Onover_drift_inChanging(Nullable<global::System.Double> value);
        partial void Onover_drift_inChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> over_drift_out
        {
            get
            {
                return _over_drift_out;
            }
            set
            {
                Onover_drift_outChanging(value);
                ReportPropertyChanging("over_drift_out");
                _over_drift_out = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("over_drift_out");
                Onover_drift_outChanged();
            }
        }
        private Nullable<global::System.Double> _over_drift_out;
        partial void Onover_drift_outChanging(Nullable<global::System.Double> value);
        partial void Onover_drift_outChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sub_status
        {
            get
            {
                return _sub_status;
            }
            set
            {
                Onsub_statusChanging(value);
                ReportPropertyChanging("sub_status");
                _sub_status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sub_status");
                Onsub_statusChanged();
            }
        }
        private global::System.String _sub_status;
        partial void Onsub_statusChanging(global::System.String value);
        partial void Onsub_statusChanged();

        #endregion
    
    }

    #endregion
    
}
