//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqltest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEQ
    {
        public string eqi_id { get; set; }
        public string eq_type { get; set; }
        public string eq_prober { get; set; }
        public string eq_tester { get; set; }
        public System.DateTime eq_release_time { get; set; }
        public string eq_comment { get; set; }
        public string status { get; set; }
        public string lot_id { get; set; }
        public string probe_card_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public string recipe { get; set; }
        public string @operator { get; set; }
        public int total_num_wafer { get; set; }
        public string fab { get; set; }
        public int tested_num_wafer { get; set; }
        public int total_num_chip { get; set; }
        public int tested_num_chip { get; set; }
        public string current_test_wafer_id { get; set; }
        public string IsWarnig { get; set; }
        public Nullable<long> current_identify { get; set; }
        public Nullable<int> expected_remain_time { get; set; }
        public Nullable<int> current_warning_identify { get; set; }
        public string eq_area { get; set; }
        public string wafer_id { get; set; }
        public Nullable<double> over_drive { get; set; }
        public string sub_status { get; set; }
    }
}
