//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqltest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEQHistory
    {
        public long identify { get; set; }
        public string eq_id { get; set; }
        public string status { get; set; }
        public string lot_id { get; set; }
        public string probe_card_id { get; set; }
        public string recipe { get; set; }
        public Nullable<int> total_num_wafer { get; set; }
        public string @operator { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> stop_time { get; set; }
        public string eq_comment { get; set; }
        public bool IsFinish { get; set; }
        public Nullable<int> tested_num_wafer { get; set; }
        public string wafer_id_in { get; set; }
        public string wafer_id_out { get; set; }
        public Nullable<double> over_drive { get; set; }
        public Nullable<double> over_drive_in { get; set; }
        public Nullable<double> over_drive_out { get; set; }
        public string sub_status { get; set; }
    }
}
