//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqltest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVerifyNote
    {
        public long SeqNo { get; set; }
        public string PCID { get; set; }
        public string WaferID { get; set; }
        public string TestVerify { get; set; }
        public Nullable<System.DateTime> TestVerifyDate { get; set; }
        public string TPS { get; set; }
        public string MAP { get; set; }
        public string RCP { get; set; }
        public string Operators { get; set; }
        public Nullable<System.DateTime> StartTimes { get; set; }
        public Nullable<System.DateTime> StopTimes { get; set; }
        public Nullable<long> TouchDo { get; set; }
        public Nullable<int> Pass { get; set; }
        public Nullable<int> Fail { get; set; }
        public string HasWarning { get; set; }
        public Nullable<int> ProbeShape { get; set; }
        public Nullable<double> over_drive { get; set; }
    }
}
